---
- hosts: localhost
  become: true

  tasks:
  - name: Running mvn clean
    shell: "mvn clean install"
    register: mvn_result

  - name: "mvn clean task output"
    debug:
     var: mvn_result
     
  - name: Running mvn package
    shell: "mvn package"
    register: mvn_result
    
  - name: create docker image using war file
    command: docker build -t plamsal90/abc-technology-cloud-c:latest .

  - name: Tag and push to docker hub
    docker_image:
    name: abc
    repository: plamsal90/abc-technology-cloud-c
    push: yes

#   - name: remove docker images form ansible server
#     command: docker rmi abc-technology-cloud:latest plamsal90/abc-technology-cloud
#     ignore_errors: yes
