---
- hosts: localhost
  become: true

  tasks:
  - name: Running mvn clean
    shell: "mvn clean install"
    register: mvn_result

  - name: "mvn clean task output"
    debug:
     var: mvn_result
     
  - name: Running mvn package
    shell: "mvn package"
    register: mvn_result
    
  - name: build docker image 
    command: docker build -t abc-technology-cloud-d . 
  
  - name: tag docker image 
    command: docker tag abc-technology-cloud-d plamsal90/abc-technology-cloud-d:latest

  - name: Push image to registry
    docker_image:
      name: abc-technology-cloud-d
      repository: plamsal90/abc-technology-cloud-d:latest
      push: yes
    
    
    
#     name: build docker image 
#     command: docker build -t docker-image . 
#     args: chdir: /opt/docker

# name: tag docker image command: docker tag docker-image tsvarma07/image:docker-image

# name: push image into docker hub 
# command: docker push tsvarma07/image:docker-image






# name: push image into docker hub 
# command: docker push tsvarma07/image:docker-image

#   - name: remove docker images form ansible server
#     command: docker rmi abc-technology-cloud:latest plamsal90/abc-technology-cloud
#     ignore_errors: yes
