---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t abc-technology-cloud:latest .
    args:
      chdir: /opt/k8s-lab

  - name: create tag to image
    command: docker tag abc-technology-cloud plamsal90/abc-technology-cloud

  - name: push image on to dockerhub
    command: docker push plamsal90/abc-technology-cloud

  - name: remove docker images form ansible server
    command: docker rmi abc-technology-cloud:latest plamsal90/abc-technology-cloud
    ignore_errors: yes
