apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-technology-cali
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-technology-cali
  template:
    metadata:
      labels:
        app: abc-technology-cali
    spec:
      containers:
        - name: java
          image: plamsal90/abc-technology-cali
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: abc-technology-cali
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: abc-technology-cali
