apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-technology-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-technology-cloud
  template:
    metadata:
      labels:
        app: abc-technology-cloud
    spec:
      containers:
        - name: java
          image: plamsal90/abc-technology-cloud
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: abc-technology-cloud
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: abc-technology-cloud
