---
- hosts: web
  become: yes
  vars: 
    username: sonal
    doc_root: /var/www/html
  tasks:

# This task will install apache http server
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Start apache2
    service:
      name: apache2
      state: started 
      enabled: yes
    when: ansible_os_family == "Debian"

